// Session code system. Two valid lengths coexist forever:
//   - 4 chars: legacy codes generated by the original hex genCode (0-9 A-F).
//     Hex is a strict subset of Crockford-32, so they validate cleanly.
//   - 8 chars: current canonical form, fresh Crockford-32.
//
// Future: a 12-char tier could be added by appending to VALID_LENGTHS and
// bumping CANONICAL_LENGTH; existing codes in storage continue to work.

import crypto from 'crypto'

// Crockford base32: 0-9 A-Z minus I L O U (32 chars total).
// I/L excluded for 1 confusion, O for 0 confusion, U for accidental profanity.
export const ALPHABET = '0123456789ABCDEFGHJKMNPQRSTVWXYZ'

export const VALID_LENGTHS = [4, 8] as const
export const CANONICAL_LENGTH = 8

export function genCode(): string {
  const buf = crypto.randomBytes(CANONICAL_LENGTH)
  let out = ''
  for (let i = 0; i < CANONICAL_LENGTH; i++) {
    out += ALPHABET[buf[i] % ALPHABET.length]
  }
  return out
}

export function normalizeCode(input: unknown): string | null {
  if (typeof input !== 'string') return null
  // Strip non-alphanumeric (kills hyphens, whitespace, punctuation), uppercase.
  const s = input.replace(/[^a-zA-Z0-9]/g, '').toUpperCase()
  if (!(VALID_LENGTHS as readonly number[]).includes(s.length)) return null
  for (const c of s) if (!ALPHABET.includes(c)) return null
  return s
}

// Same validation as normalizeCode but with a structured failure reason so
// user-facing input forms can show a specific message instead of a generic
// "not found." Server routes don't need this distinction — they all map a
// failed normalize to 404. Empty/whitespace-only input → 'empty'; right
// alphabet but wrong length → 'invalid-length'; chars outside Crockford
// (I, L, O, U, or non-alphanumerics that survive the strip) → 'invalid-char'.
export type CodeValidationResult =
  | { ok: true; code: string }
  | { ok: false; error: 'empty' | 'invalid-length' | 'invalid-char' }

export function validateCodeInput(input: string): CodeValidationResult {
  const s = input.replace(/[^a-zA-Z0-9]/g, '').toUpperCase()
  if (s.length === 0) return { ok: false, error: 'empty' }
  for (const c of s) if (!ALPHABET.includes(c)) return { ok: false, error: 'invalid-char' }
  if (!(VALID_LENGTHS as readonly number[]).includes(s.length)) return { ok: false, error: 'invalid-length' }
  return { ok: true, code: s }
}

export function formatCode(stored: string | null | undefined): string {
  // 4-char legacy: bare. 8-char canonical: hyphenated for groupability.
  // Null/undefined input → empty string so callers can render unconditionally
  // without TypeError (e.g. for orphaned wines whose session was deleted).
  if (!stored) return ''
  if (stored.length === 4) return stored
  if (stored.length === 8) return `${stored.slice(0, 4)}-${stored.slice(4)}`
  return stored
}

// Visual transform for the live "type a code" input. Strips non-alphanumerics
// so paste of "ABCD-1234" or "abcd 1234" works, uppercases, caps at 8 chars,
// and inserts a hyphen between groups of 4 once length passes 4. Submit code
// runs the result through normalizeCode which is hyphen-tolerant anyway.
export function formatCodeInput(raw: string): string {
  const stripped = raw.replace(/[^a-zA-Z0-9]/g, '').toUpperCase().slice(0, CANONICAL_LENGTH)
  if (stripped.length <= 4) return stripped
  return `${stripped.slice(0, 4)}-${stripped.slice(4)}`
}
