// Run: node scripts/seed-badges.mjs
import { createRequire } from 'module'
const require = createRequire(import.meta.url)

// Inline all badge definitions to avoid TS compilation
const ALL_BADGES = [
  {id:'first_pour',name:'First Pour',description:"Rate your very first wine. Every legend starts somewhere.",icon:'🍷',category:'first_steps',rarity:'common',xp_reward:25},
  {id:'first_session',name:'Open the Table',description:'Join your first tasting session.',icon:'🪑',category:'first_steps',rarity:'common',xp_reward:25},
  {id:'first_host',name:'The Host',description:'Create and host your first tasting session.',icon:'🎩',category:'first_steps',rarity:'common',xp_reward:50},
  {id:'first_5star',name:'Perfect Taste',description:'Award your first ever 5-star rating.',icon:'⭐',category:'first_steps',rarity:'common',xp_reward:30},
  {id:'first_notes',name:'The Wordsmith',description:'Write your first tasting note.',icon:'📝',category:'first_steps',rarity:'common',xp_reward:20},
  {id:'first_bookmark',name:'Saved for Later',description:'Bookmark your first wine.',icon:'🔖',category:'first_steps',rarity:'common',xp_reward:15},
  {id:'first_photo',name:'Shoot the Label',description:'Add a bottle photo to a wine.',icon:'📷',category:'first_steps',rarity:'common',xp_reward:20},
  {id:'first_hof',name:'Hall Bound',description:'Get a wine into the Hall of Fame.',icon:'🏛',category:'first_steps',rarity:'uncommon',xp_reward:75},
  {id:'rated_10',name:'Getting Warmed Up',description:'Rate 10 wines. The palate is awakening.',icon:'🌡',category:'quantity',rarity:'common',xp_reward:40},
  {id:'rated_25',name:'Quarter Century',description:"Rate 25 wines. You're developing a serious habit.",icon:'🥈',category:'quantity',rarity:'common',xp_reward:60},
  {id:'rated_50',name:'Half a Hundred',description:'Rate 50 wines. Your opinion carries weight.',icon:'🎯',category:'quantity',rarity:'uncommon',xp_reward:100},
  {id:'rated_100',name:'The Hundred',description:"100 wines rated. You're not messing around.",icon:'💯',category:'quantity',rarity:'uncommon',xp_reward:150},
  {id:'rated_250',name:'Quarter Millennial',description:"250 wines. At this point it's a lifestyle.",icon:'🏆',category:'quantity',rarity:'rare',xp_reward:250},
  {id:'rated_500',name:'The Five Hundred',description:"500 ratings. Your cellar journal rivals a sommelier's.",icon:'🍾',category:'quantity',rarity:'epic',xp_reward:400},
  {id:'rated_1000',name:'Thousand Oaks',description:'1000 ratings. You are the algorithm.',icon:'🌳',category:'quantity',rarity:'legendary',xp_reward:750},
  {id:'sessions_5',name:'Social Animal',description:'Participate in 5 tasting sessions.',icon:'🦁',category:'quantity',rarity:'common',xp_reward:50},
  {id:'sessions_10',name:'Table Regular',description:'Participate in 10 tasting sessions.',icon:'🪑',category:'quantity',rarity:'uncommon',xp_reward:100},
  {id:'sessions_25',name:'The Connoisseur Circuit',description:'Participate in 25 sessions. The table knows your face.',icon:'🎭',category:'quantity',rarity:'rare',xp_reward:200},
  {id:'hosted_5',name:'Host with the Most',description:'Host 5 tasting sessions.',icon:'🏠',category:'quantity',rarity:'uncommon',xp_reward:100},
  {id:'hosted_10',name:'Master of Ceremonies',description:'Host 10 sessions. You set the stage.',icon:'🎙',category:'quantity',rarity:'rare',xp_reward:200},
  {id:'bookmarks_20',name:'The Collector',description:'Save 20 wines to your collection.',icon:'📚',category:'quantity',rarity:'uncommon',xp_reward:75},
  {id:'bookmarks_50',name:'Cellar Master',description:"Save 50 wines. You're curating something special.",icon:'🗄',category:'quantity',rarity:'rare',xp_reward:150},
  {id:'type_red_10',name:'Red-Handed',description:'Rate 10 red wines. Tannin is your middle name.',icon:'🍷',category:'types',rarity:'common',xp_reward:40},
  {id:'type_white_10',name:'White Collar',description:'Rate 10 white wines. Crisp and collected.',icon:'🥂',category:'types',rarity:'common',xp_reward:40},
  {id:'type_spark_10',name:'Bubbles & Troubles',description:'Rate 10 sparkling wines.',icon:'🍾',category:'types',rarity:'common',xp_reward:40},
  {id:'type_rose_10',name:'Rosé All Day',description:'Rate 10 rosés. No shame, only gains.',icon:'🌸',category:'types',rarity:'common',xp_reward:40},
  {id:'type_nonalc_5',name:'Beyond the Vine',description:'Rate 5 non-alcoholic wines.',icon:'🌿',category:'types',rarity:'uncommon',xp_reward:60},
  {id:'type_all',name:'The Full Spectrum',description:'Rate at least one of every wine type.',icon:'🌈',category:'types',rarity:'uncommon',xp_reward:100},
  {id:'type_red_50',name:'Red Obsessed',description:'50 red wines. The dark side has you.',icon:'❤',category:'types',rarity:'rare',xp_reward:150},
  {id:'type_spark_25',name:'Champagne Problems',description:'25 sparkling wines. Celebrations on demand.',icon:'✨',category:'types',rarity:'uncommon',xp_reward:100},
  {id:'unique_grapes_10',name:'Grape Explorer',description:'Rate wines from 10 different grape varieties.',icon:'🔭',category:'types',rarity:'uncommon',xp_reward:100},
  {id:'unique_grapes_25',name:'Ampelographer',description:'25 distinct grape varieties.',icon:'🧬',category:'types',rarity:'rare',xp_reward:200},
  {id:'unique_styles_8',name:'Style Icon',description:'Rate wines across 8 different styles.',icon:'💅',category:'types',rarity:'uncommon',xp_reward:80},
  {id:'perfect_5',name:'Five of Them',description:'Give out 5 perfect 5-star ratings.',icon:'🌟',category:'scoring',rarity:'common',xp_reward:50},
  {id:'perfect_20',name:'Standards Are High',description:'20 five-star ratings.',icon:'⭐',category:'scoring',rarity:'uncommon',xp_reward:100},
  {id:'perfect_50',name:'Generous Soul',description:'50 wines worthy of perfection.',icon:'💫',category:'scoring',rarity:'rare',xp_reward:200},
  {id:'harsh_critic',name:'Harsh Critic',description:'Give a 1-star rating. Not everything deserves love.',icon:'💀',category:'scoring',rarity:'common',xp_reward:20},
  {id:'hof_3',name:'Triple Crown',description:'Get 3 wines into the Hall of Fame.',icon:'👑',category:'scoring',rarity:'rare',xp_reward:200},
  {id:'hof_10',name:'Hall of Fame Legend',description:'10 wines in the Hall of Fame.',icon:'🏆',category:'scoring',rarity:'legendary',xp_reward:500},
  {id:'high_avg',name:'Glass Half Full',description:'Maintain an average score above 4.0 across 20+ ratings.',icon:'😊',category:'scoring',rarity:'uncommon',xp_reward:100},
  {id:'tannic_titan',name:'Tannic Titan',description:'Consistently rate tannins above 3 in 15+ red wines.',icon:'💪',category:'flavour',rarity:'uncommon',xp_reward:80},
  {id:'acid_freak',name:'Acid Freak',description:'Consistently score high acidity in 15+ wines.',icon:'⚡',category:'flavour',rarity:'uncommon',xp_reward:80},
  {id:'oak_addict',name:'Oak Addict',description:'High oak scores across 15+ wines.',icon:'🪵',category:'flavour',rarity:'uncommon',xp_reward:80},
  {id:'floral_fanatic',name:'Floral Fanatic',description:'High floral notes in 15+ wines.',icon:'🌸',category:'flavour',rarity:'uncommon',xp_reward:80},
  {id:'fruit_bomb',name:'Fruit Bomb Aficionado',description:'Consistently high fruit scores across 20 wines.',icon:'🍓',category:'flavour',rarity:'uncommon',xp_reward:80},
  {id:'mineral_hunter',name:'Mineral Hunter',description:'Seeking minerals in 10+ whites.',icon:'🪨',category:'flavour',rarity:'rare',xp_reward:120},
  {id:'earth_mover',name:'Earth Mover',description:'High earth scores across 15+ wines.',icon:'🌍',category:'flavour',rarity:'uncommon',xp_reward:80},
  {id:'big_table',name:'The Big Table',description:'Participate in a session with 5 or more people.',icon:'🎊',category:'social',rarity:'uncommon',xp_reward:75},
  {id:'crowd_pleaser',name:'Crowd Pleaser',description:'Host a session with 8+ participants.',icon:'🎪',category:'social',rarity:'rare',xp_reward:150},
  {id:'blind_believer',name:'Blind Believer',description:'Participate in a blind tasting session.',icon:'🙈',category:'social',rarity:'uncommon',xp_reward:100},
  {id:'notes_10',name:'Scribbler',description:'Write tasting notes for 10 wines.',icon:'✍',category:'craft',rarity:'common',xp_reward:50},
  {id:'notes_50',name:'The Chronicler',description:'Write tasting notes for 50 wines.',icon:'📰',category:'craft',rarity:'uncommon',xp_reward:100},
  {id:'notes_100',name:'The Novelist',description:'100 tasting notes.',icon:'📖',category:'craft',rarity:'rare',xp_reward:200},
  {id:'long_note',name:'Purple Prose',description:'Write a tasting note over 200 characters.',icon:'🖋',category:'craft',rarity:'uncommon',xp_reward:60},
  {id:'photos_10',name:'Label Lover',description:'Add photos to 10 wines.',icon:'📸',category:'craft',rarity:'common',xp_reward:50},
  {id:'photos_30',name:'Instagram Sommelier',description:'Photos on 30 wines.',icon:'🎨',category:'craft',rarity:'uncommon',xp_reward:100},
  {id:'veteran_30',name:'One Month In',description:'Active member for 30 days.',icon:'📅',category:'loyalty',rarity:'common',xp_reward:50},
  {id:'veteran_90',name:'Quarter Year',description:'Active member for 90 days.',icon:'🗓',category:'loyalty',rarity:'uncommon',xp_reward:100},
  {id:'veteran_365',name:'The Vintage',description:'A full year of tasting.',icon:'🌞',category:'loyalty',rarity:'rare',xp_reward:300},
  {id:'monthly_3',name:'Three Months Running',description:'Rated wines in 3 consecutive months.',icon:'📊',category:'loyalty',rarity:'uncommon',xp_reward:100},
  {id:'monthly_12',name:'Year-Round Sipper',description:'Rated wines every month for a year.',icon:'🏅',category:'loyalty',rarity:'legendary',xp_reward:500},
]

const esc = s => s.replace(/'/g, "''")
const vals = ALL_BADGES.map(b =>
  `('${esc(b.id)}','${esc(b.name)}','${esc(b.description)}','${esc(b.icon)}','${esc(b.category)}','${esc(b.rarity)}',${b.xp_reward})`
).join(',\n')

process.stdout.write(`INSERT INTO badges (id,name,description,icon,category,rarity,xp_reward) VALUES\n${vals}\nON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description, icon=EXCLUDED.icon, xp_reward=EXCLUDED.xp_reward;\n`)
